config/routes.rb
Rails.application.routes.draw do

  apipie
  # if Rails.env.development? || Rails.env.test?

    # Beacons
    get   '/beacon/:key',     to: 'beacons#edit',     as: 'edit_beacon'
    patch '/beacon/:key',     to: 'beacons#update',   as: 'beacon'
    get   '/beacon/success',  to: 'beacons#success',  as: 'beacon_success'

    # Businesses
    get '/business', to: 'businesses#edit', as: 'edit_business'
    resources :businesses, only: [:new, :create, :update]

    # Customers
    get  '/customers/:status/(:export/:list)',  to: 'customers#index',   as: 'customers',  constraints: {status: /(all|active|inactive)/}, defaults: {status: 'all'}
    post '/customers/import',                   to: 'customers#import',  as: 'import_customers'

    # Greetings
    resources :greetings, except: [:show]


    # All Receipts
    resources :receipts, only: [:index, :show]

    # All Campaigns
    get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
    get '/campaigns/new/:type',         to: 'campaigns#new',    as: 'new_campaign', constraints: {type: /(coupon|reward|special)/}, defaults: {type: 'coupon'}
    resources :campaigns, except: [:index, :new]

    # Locations and Locationable Routes
    resources :locations, except: [:destroy] do
      get     '/subscription/success',    to: 'subscriptions#success',   as: 'subscription_success'
      get     '/subscription',            to: 'subscriptions#show',      as: 'subscription'
      get     '/subscription/new',        to: 'subscriptions#new',       as: 'new_subscription'
      post    '/subscription/new',        to: 'subscriptions#create',    as: 'subscriptions'
      delete  '/subscription/cancel',     to: 'subscriptions#destroy',   as: 'cancel_subscription'
      patch '/confirm',   to: 'locations#confirm', as: 'confirm'

      # Locationable routes
      get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
      resources :campaigns, only: :show
    end


    # Users
    devise_for :users, skip: [:sessions], controllers: {
      confirmations:  'users/confirmations',
      registrations:  'users/registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

    devise_scope :user do
      get '/users/login'     => 'devise/sessions#new',     as: :new_user_session
      post '/users/login'    => 'devise/sessions#create',  as: :user_session
      delete '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session

      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup'   => 'omniauth_callbacks#setup'
    end

    get '/users/toggleSidebar', to: "users#toggleSidebar"
    post '/users/endTour', to: "users#endTour"

    # Admins
    devise_for :admins

    namespace :admin do
      root 'pages#dashboard'
      resources :receipts, only: [:index, :update, :destroy]
    end

    # Normal Pages
    get '/lock_business/:id',   to: 'businesses#lock'
    get '/locked',   to: 'pages#locked_business',  as: 'locked_business'
    get '/subscription_canceled',   to: 'pages#subscription_canceled',  as: 'subscription_canceled'


    # Root
    root 'pages#dashboard'
  # end


  ## API
  namespace :api do
    api versions: 1, module: "v1" do
      # Customer actions
      post '/customers/sign_in',            to: 'customers#sign_in'
      post '/customers/sign_out',           to: 'customers#sign_out'
      post '/customers/check_in',           to: 'customers#check_in'
      post '/customers/check_out',          to: 'customers#check_out'
      post '/customers/notification_token', to: 'customers#notification_token'
      get '/customers/profile',             to: 'customers#show'
      get '/customers/feed',                to: 'customers#feed'
      get '/customers/visits',              to: 'customers#visits'

      # Temp test for notifications
      # get '/customers/notification',        to: 'customers#get_notification'

      # Finds a location via UID
      get '/beacons/:uid/location',            to: 'locations#show'

      # Locations
      get '/locations/:id',                     to: 'locations#show'
      get '/locations/:id/campaigns',           to: 'campaigns#index'
      # Fetch nearest 20 beacons. Similar to fetch map, but return top 20 by proximity
      get '/locations/near/:lat/:lon',          to: 'locations#fetch_nearby', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}
      get '/locations/map/:lat/:lon/:distance', to: 'locations#fetch_map', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}

      # Campaigns
      resources :campaigns, only: [:show]

      # Receipts
      post '/receipts',              to: 'receipts#create'
      get  '/receipts(/:status)',   to: 'receipts#index', defaults: {status: 'untouched'}

      # Redemptions
      resources :redemptions, only: [:index, :create]

      # Referrals
      resources :share_links, only: [:show, :create]
    end
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  http_basic_authenticate_with name: APP_CONFIG['lock_business_username'], password: APP_CONFIG['lock_business_password'], only: :lock
  skip_before_action :authenticate_user!, only: [:lock]
  skip_before_action :check_business_status, only: [:lock]
  skip_before_action :set_current_location, only: [:lock]

  before_action :set_business, only: [:show, :edit, :update]

  def lock
    business = Business.find(params[:id])
    business.locked!
    render html: "OK"
  end

  # GET /businesses/new
  def new
    if !current_user.business.nil?
      redirect_to root_url, alert: "You have already created your business."
    end

    @business = Business.new
    @business.locations.build
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    # Create each image
    # copied from locations controller
    if params[:image_datafiles]
      params[:image_datafiles].each do |image|
        @business.image = convert_data_uri_to_upload(image) unless image.blank?
      end
    end
    ##

    respond_to do |format|
      if @business.save
        format.html { redirect_to new_location_path, notice: 'Business was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    # Update each image
    ## copied from locations controller
    if params[:image_datafiles]
      params[:image_datafiles].each do |image|
        @business.image = convert_data_uri_to_upload(image) unless image.blank?
      end
    end
    ##

    # The user is publishing the business
    if params[:publish]
      publish_errors = []
      %w(location campaign greeting).each do |child|
        publish_errors.push "Your business must have at least 1 #{child}" unless @business.send("#{child}s").exists?
      end

      if publish_errors.empty?
        @business.status = 'published'
        notice = 'Your store has been saved and published! Your location(s) are now visible in the Zippy Spot app.'
      else
        notice = "You're not quite ready to publish your store yet. Your locations, campaigns, and greetings must first be setup."
      end
    end


    respond_to do |format|
      @business.image = convert_data_uri_to_upload(params[:image_datafile]) unless params[:image_datafile].blank?

      if @business.update(business_params)

        if params[:facebook_page]
          current_user.set_facebook_page(params[:facebook_page])
        end

        if params[:publish] && params[:shareText] && params[:share_to]
          message = params[:shareText]
          current_user.tweet(message) if params[:share_to]["twitter"]
          current_user.post_to_facebook_page(message) if params[:share_to]["facebook"]
        end


        format.html { redirect_to edit_business_path, notice: notice || 'Business was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = current_user.business
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :logo_filename, :primary_color, :secondary_color, :website, :facebook, :yelp_url, :twitter,
        :locations_attributes => [:address, :address2, :city, :state, :zipcode]
      )
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
	
	def connect_identity_link(provider)
		if current_user.send("#{provider}").nil?
			link_to "Connect", user_omniauth_upgrade_path( provider ), class: "btn btn-default connect"
		else
			content_tag :div, raw("Connected<br>(" + current_user.send(provider).name + ")"), class: "btn connected"
		end
	end

end

app/views/businesses/_form.html.erb
<!-- Business profile FORM Start -->
<%= form_for(@business, multipart: true, html: {class: 'form'} ) do |f| %>
  <%= form_errors_for @business %>

  <%= wrapper do %>
    <%= section_header 'Your Business' %>
    <div class="toggle-section">

      <%= fr 'Business Name', f.text_field(:name, class: 'businessName') %>

      <%= fr "Logo (click to edit)", id: "logo-row" do %>
        <%= image_tag @business.image.url(:index), style: "width:300px", id: "saved_image_1", class: "js-savedImage fit pointer thumbnail", data: {toggle: 'modal', target: "#cropImageModal-1"} %>
        <%= hidden_field_tag 'image_datafiles[]', "", id: "image_datafiles_1", data: {uploadtarget: "cropImageModal-1"} %>
      <% end %>

      <%= render 'shared/toggle_section_btns' %>
    </div>
  <% end %>

  <%= wrapper :dark do %>
    <%= section_header "Style Options" %>
    <div class="toggle-section">
      
      <div class="row contPaletteColors">
        <div class="col-xs-12 col-sm-3">
          <label>Colors From Logo <a href="#" id="refreshDetectedColors" title="Refresh"><i class="fa fa-refresh"></i></a></label>
        </div>
        <div class="col-xs-12 col-sm-9 paletteColors">
          <div class="color"></div>
          <div class="color"></div>
          <div class="color"></div>
          <div class="color"></div>
          <div class="color"></div>
        </div>
      </div>
      
      <%= fr "Primary Color" do %>
        <%= f.text_field :primary_color, id: 'colorPicker1', placeholder: '#FFF' %>
      <% end %>
      
      <%= fr "Secondary Color" do %>
        <%= f.text_field :secondary_color, id: 'colorPicker2', placeholder: '#FFF' %>
      <% end %>
      
      <div class="row">
        <div class="col-md-offset-3 col-md-9 col-xs-12 preview">
          <%= link_to 'preview your mobile page', '#', class: 'preview-campaign caps', data: {toggle: 'modal', target: '#previewModal'} %>
        </div>
      </div>

      <%= render 'shared/toggle_section_btns' %>
    </div> 
  <% end %> <%# -wrapper dark %>


  <%= wrapper do %>
    <%= section_header "Social Settings" %>
    <div class="toggle-section">
      <%= fr "WEBSITE", f.text_field(:website, class: 'website', placeholder: 'http://') %>
      <%= fr "Yelp URL", f.text_field(:yelp_url, class: 'yelp_url', placeholder: 'http://www.yelp.com/...') %>
      <%= fr "TWITTER URL", f.text_field(:twitter, class: 'twitterUrl', placeholder: 'http://') %>
      <%= fr "FACEBOOK URL", f.text_field(:facebook, class: 'facebookUrl', placeholder: 'http://') %>

      <%= render 'shared/toggle_section_btns' %>
    </div>
  <% end %>


  <%= wrapper :dark do %>
    <%= section_header "Integrations",
        desc: "Please save all changes to your profile before connecting to an app below." %>

    <div class="toggle-section">
      
      <div class="row mt3">
        <div class="col-xs-12 col-sm-3 mb1-5 text-center">
          <%= image_tag('facebook.png') %>
          <%= connect_identity_link("facebook") %>
        </div>
        <div class="col-xs-12 col-sm-3 mb1-5 text-center">
          <%= image_tag('twitter.png') %>
          <%= connect_identity_link("twitter") %>
        </div>
        <div class="col-xs-12 col-sm-3 mb1-5 text-center">
          <%= image_tag('mailchimp.png') %>
          <%= connect_identity_link("mailchimp") %>
        </div>
        <div class="col-xs-12 col-sm-3 mb1-5 text-center">
          <%= image_tag('constantcontact.png') %>
          <%= connect_identity_link("constantcontact") %>
        </div>
      </div>
      
      <% if current_user.facebook_pages && current_user.facebook.page_token == "" %>
        <%= section_header "Select a Facebook Page" %>
      
        <%= fr "Facebook Page" do %>
          <% current_user.facebook_pages.each do |page| %>
            <%= radio_button_tag 'facebook_page', page['id'] %> <%= page['name'] %><br />
          <% end %>
        <% end %>
      <% end %>

      <%= render 'shared/toggle_section_btns' %>
    </div> <%# /.toggle-section &>
    
    <%# Form save button %>
    <div class="row py4">
      <div class="col-xs-12 text-center">
        <%= f.button %>
      </div>
      <%# SHOW THE PUBLISH BUTTON %>
      <% if @business.unpublished? && !@business.new_record? %>
        <%# TEMPORARY: Hide the publish button if unable to publish. %>
        <%#            This should be a boolean method in the business object. %>
        <%
        publish_errors = []
        %w(location campaign greeting).each do |child|
          publish_errors.push "Your business must have at least 1 #{child}" unless @business.send("#{child}s").exists?
        end

        if publish_errors.empty? %>
          <div class="col-xs-12 text-center">
            <%# SHOW SHARE_TO MODAL IF CONNECTED TO FB OR TWITTER %>
            <% if current_user.facebook || current_user.twitter %>
              <%= link_to 'Save and Publish Profile!', "#", class: 'btn publish', data: {toggle: 'modal', target: '#shareModal'}  %>
            <% else %>
              <%= f.button 'Save and Publish Profile!', name: 'publish', class: 'publish' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

  <% end %> <%# -wrapper dark %>

  <%# GALLERY MODAL %>
  <%= modal :large, id: "shareModal", title: "Announce your business!",
      body: capture { %>
        <div class="row">
          <div class="col-xs-12">
            <p>Now that you are publishing your business on Zippy Spot, you can announce to your followers about the big move!</p>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <textarea name="shareText">We have just published our business on Zippy Spot!</textarea>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <% %w(facebook twitter).each do |i| %>
              <% unless current_user.send(i).nil? %>
                <div class="cbox">
                  <%= check_box_tag "share_to[#{i}]", 1, true, id: "share_to_#{i}" %>
                  <label for="share_to_<%= i %>">Share to <%= i.humanize %></label>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
  <% }, footer: capture { %>
    <%= f.button 'Share and Publish!', name: 'publish', class: 'publish' %>
  <% } %>

<% end %> <%# -form %>


<%# Mobile preview %>
<%= render 'mobile_preview', business: @business %>


<%# CROP MODAL %>
<%= render 'shared/crop_modal', resource: @business, id: "cropImageModal-1" %>

app/views/businesses/_mobile_preview.html.erb
<!-- Modal -->
<div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Mobile Preview</h4>
      </div>

      <div class="modal-body">
        <!-- <div class="container"> -->
        <div class="mobilePreview_device-wrap">
          <div class="modal-container">
          <!-- TODO: After uploading an image, the page has to be updated for the new image to show here -->
            <div class="mobilePreview">

              <div class="mobilePreview-head">
                <div class="previewPrimaryBg mobilePreview-header_bg-wrap" style="background-color: #<%= current_user.business.primary_color %>">

                  <!-- <h1 class="h4 center c-white" style="padding-top: 14px"><%= current_user.business.name %></h1> -->
                  <div class="mobilePreview_header" id="preview-image-as-bg" style="background-image: url('<%= image_path('mobile-preview--header.jpg') %>')"></div>
                  <div class="mobilePreview_bg" style="background-image: url('<%= business.image.url(:index) %>')"></div>

                  <div class="contain" style="padding: 20px 0">
                    <div class="row mx-auto" style="max-width: 92%">
                      <div class="col-xs-5"><%= image_tag business.image.url(:index), id: "preview-image-as-image", class: "fit", style: "border-radius: 50%" %></div>
                      <p class="col-xs-7 c-white light" style="padding-top: 25px; font-size: 16px">123 Sesame St. New York, NY 11211</p>
                    </div>
                  </div>
                  <p class="center c-white relative" style="margin-bottom: 25px; z-index: 1">
                    <span class="light">Reward Points</span> <span style="font-size: 110%; margin-left: 5px">314</span> <span class="inline-block" style="padding: 0 7px">|</span> <span class="light">Check-ins</span> <span style="font-size: 110%; margin-left: 5px">42</span>
                  </p>
                  <ul class="mx-auto fit center mobilePreview-nav_ul row">
                    <li class="caps inline-block center c-white light col-xs-4">Specials</li>
                    <li class="caps inline-block center c-white light col-xs-4">Coupons</li>
                    <li class="caps inline-block center c-white active col-xs-4">Rewards</li>
                  </ul>
                  <div style="height: 10px; background-color: white; position: relative; bottom: 0; width: 100%"></div>
                </div>
                <div class="bg-white center" style="padding-top: 10px; padding-bottom: 18px; font-size: 18px; border-bottom: solid 2px #bebebe">
                  <span class="light">Current Balance:</span> <span style="color: orange; font-size: 110%">314<span class="light small">pts</span></span>
                </div>
              </div>

              <div class="container" style="padding: 0">
                <div class="mobilePreview-panel row">
                  <div class="mobilePreview_banner">Redeem</div>
                  <div class="mobilePreview_points col-xs-3">
                    <div class="mobilePreview_points-count light">2</div>
                    <div class="mobilePreview_points-label">Points</div>
                  </div>
                  <div class="mobilePreview_panel-text col-xs-9 light">Have a latte on the house!</div>
                </div>
                <div class="mobilePreview-panel row">
                  <div class="mobilePreview_points col-xs-3">
                    <div class="mobilePreview_points-count light">500</div>
                    <div class="mobilePreview_points-label">Points</div>
                  </div>
                  <div class="mobilePreview_panel-text col-xs-9 light">Treat your friend for free</div>
                </div>
              </div>
              <div class="mobilePreview_footer" style="background-image: url('<%= image_path('mobile-preview--footer-2.jpg') %>')"></div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/businesses/edit.html.erb
<% content_for(:page_title) { "Business Profile" } %>

<%= render 'form' %>

<% if current_user.business.unpublished? && !notice.blank? %>
	<%= hopscotch "businesses-edit-updated" %>
<% else %>
	<%= hopscotch %>
<% end %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Businesses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Published</th>
      <th>Logo filename</th>
      <th>Primary color</th>
      <th>Secondary color</th>
      <th>Website</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.user %></td>
        <td><%= business.name %></td>
        <td><%= business.published %></td>
        <td><%= business.logo_filename %></td>
        <td><%= business.primary_color %></td>
        <td><%= business.secondary_color %></td>
        <td><%= business.website %></td>
        <td><%= business.facebook %></td>
        <td><%= business.twitter %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<h4>Set Up Your Business Profile</h4>
	</div>
</div>

<%= form_for(@business) do |f| %>
	<%= form_errors_for @business %>

  <%= fr "Name", f.text_field(:name) %>
  <%= fr "Website", f.text_field(:website) %>

  <div class="row">
  	<div class="col-xs-12 text-center"><%= f.button "Create and Go to Dashboard" %></div>
  </div>
<% end %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @business.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Published:</strong>
  <%= @business.published %>
</p>

<p>
  <strong>Logo filename:</strong>
  <%= @business.logo_filename %>
</p>

<p>
  <strong>Primary color:</strong>
  <%= @business.primary_color %>
</p>

<p>
  <strong>Secondary color:</strong>
  <%= @business.secondary_color %>
</p>

<p>
  <strong>Website:</strong>
  <%= @business.website %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @business.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @business.twitter %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>