config/routes.rb
Rails.application.routes.draw do

  apipie
  # if Rails.env.development? || Rails.env.test?

    # Beacons
    get   '/beacon/:key',     to: 'beacons#edit',     as: 'edit_beacon'
    patch '/beacon/:key',     to: 'beacons#update',   as: 'beacon'
    get   '/beacon/success',  to: 'beacons#success',  as: 'beacon_success'

    # Businesses
    get '/business', to: 'businesses#edit', as: 'edit_business'
    resources :businesses, only: [:new, :create, :update]

    # Customers
    get  '/customers/:status/(:export/:list)',  to: 'customers#index',   as: 'customers',  constraints: {status: /(all|active|inactive)/}, defaults: {status: 'all'}
    post '/customers/import',                   to: 'customers#import',  as: 'import_customers'

    # Greetings
    resources :greetings, except: [:show]


    # All Receipts
    resources :receipts, only: [:index, :show]

    # All Campaigns
    get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
    get '/campaigns/new/:type',         to: 'campaigns#new',    as: 'new_campaign', constraints: {type: /(coupon|reward|special)/}, defaults: {type: 'coupon'}
    resources :campaigns, except: [:index, :new]

    # Locations and Locationable Routes
    resources :locations, except: [:destroy] do
      get     '/subscription/success',    to: 'subscriptions#success',   as: 'subscription_success'
      get     '/subscription',            to: 'subscriptions#show',      as: 'subscription'
      get     '/subscription/new',        to: 'subscriptions#new',       as: 'new_subscription'
      post    '/subscription/new',        to: 'subscriptions#create',    as: 'subscriptions'
      delete  '/subscription/cancel',     to: 'subscriptions#destroy',   as: 'cancel_subscription'
      patch '/confirm',   to: 'locations#confirm', as: 'confirm'

      # Locationable routes
      get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
      resources :campaigns, only: :show
    end


    # Users
    devise_for :users, skip: [:sessions], controllers: {
      confirmations:  'users/confirmations',
      registrations:  'users/registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

    devise_scope :user do
      get '/users/login'     => 'devise/sessions#new',     as: :new_user_session
      post '/users/login'    => 'devise/sessions#create',  as: :user_session
      delete '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session

      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup'   => 'omniauth_callbacks#setup'
    end

    get '/users/toggleSidebar', to: "users#toggleSidebar"
    post '/users/endTour', to: "users#endTour"

    # Admins
    devise_for :admins

    namespace :admin do
      root 'pages#dashboard'
      resources :receipts, only: [:index, :update, :destroy]
    end

    # Normal Pages
    get '/lock_business/:id',   to: 'businesses#lock'
    get '/locked',   to: 'pages#locked_business',  as: 'locked_business'
    get '/subscription_canceled',   to: 'pages#subscription_canceled',  as: 'subscription_canceled'


    # Root
    root 'pages#dashboard'
  # end


  ## API
  namespace :api do
    api versions: 1, module: "v1" do
      # Customer actions
      post '/customers/sign_in',            to: 'customers#sign_in'
      post '/customers/sign_out',           to: 'customers#sign_out'
      post '/customers/check_in',           to: 'customers#check_in'
      post '/customers/check_out',          to: 'customers#check_out'
      post '/customers/notification_token', to: 'customers#notification_token'
      get '/customers/profile',             to: 'customers#show'
      get '/customers/feed',                to: 'customers#feed'
      get '/customers/visits',              to: 'customers#visits'

      # Temp test for notifications
      # get '/customers/notification',        to: 'customers#get_notification'

      # Finds a location via UID
      get '/beacons/:uid/location',            to: 'locations#show'

      # Locations
      get '/locations/:id',                     to: 'locations#show'
      get '/locations/:id/campaigns',           to: 'campaigns#index'
      # Fetch nearest 20 beacons. Similar to fetch map, but return top 20 by proximity
      get '/locations/near/:lat/:lon',          to: 'locations#fetch_nearby', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}
      get '/locations/map/:lat/:lon/:distance', to: 'locations#fetch_map', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}

      # Campaigns
      resources :campaigns, only: [:show]

      # Receipts
      post '/receipts',              to: 'receipts#create'
      get  '/receipts(/:status)',   to: 'receipts#index', defaults: {status: 'untouched'}

      # Redemptions
      resources :redemptions, only: [:index, :create]

      # Referrals
      resources :share_links, only: [:show, :create]
    end
  end

end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
  include Locationable
  
  has_many :locations, dependent: :nullify
  belongs_to :campaign
  belongs_to :business

  before_validation :generate_campaign_wait_time!

  validates_presence_of :welcome_message, :exit_message
  validates :campaign_wait_time, numericality: { greater_than: 0 }, unless: "campaign_id.to_i == 0"
  validates :welcome_wait_time, numericality: { greater_than: 0 }
  validates :welcome_message, :exit_message, length: {maximum: 35}


  def welcome_wait_time
    %w(month week day).each do |span|
      if self[:welcome_wait_time] % 1.send(span) == 0
        return span
      end
    end

    # Default
    'day'
  end


  def welcome_wait_time=(span)
    time_span = case span
    when 'day'    then 1.day
    when 'week'   then 1.week
    when 'month'  then 1.month
    else 1.day
    end

    self[:welcome_wait_time] = time_span.to_i
  end


  private
    def generate_campaign_wait_time!
      quantity = (self[:campaign_wait_time_quantity].to_i > 0) ? self[:campaign_wait_time_quantity].to_i : 1
      span     = (%w(day days week weeks month months).include?(self[:campaign_wait_time_span])) ? self[:campaign_wait_time_span] : 'days'

      time_span = case span
      when 'day',   'days'    then quantity.day.to_i
      when 'week',  'weeks'   then quantity.week.to_i
      when 'month', 'months'  then quantity.month.to_i
      end

      self[:campaign_wait_time] = time_span
    end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: [:edit, :update, :destroy]
  before_action :set_campaigns, only: [:edit, :update, :new, :create]

  def index
    @greetings = current_user.business.greetings
  end

  def new
    @greeting = current_user.business.greetings.build
  end

  def edit
  end

  def create
    @greeting = Greeting.new(greeting_params)
    @greeting.business = current_user.business

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to greetings_path, notice: 'Greeting was successfully created!' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to edit_greeting_path(@greeting), notice: 'Greeting was successfully updated.' }
        format.json { render :edit, status: :ok, greeting: @greeting }
      else
        format.html { render :edit }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @greeting.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'greeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_greeting
      @greeting = current_user.business.greetings.find(params[:id])
    end

    def set_campaigns
      @campaigns = current_user.business.campaigns
    end

    def greeting_params
      params.require(:greeting).permit(:welcome_message, :welcome_reward, :welcome_reward_freq, :welcome_wait_time, :campaign_wait_time_quantity, :campaign_wait_time_span, :exit_message, :campaign_id, :exit_freq_days, :exit_freq_type)
    end
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/_form.html.erb
<%= form_for(@greeting, html: {class: 'notify-form'}) do |f| %>
  <%= form_errors_for @greeting %>

	<%= wrapper do %>
	  <%= render 'form_fields', f: f, greeting_campaign: @greeting.campaign %>

		<div class="row">
			<div class="col-xs-12 text-center">
			  <%= f.button :submit, id: "tour-button", class: "btn btn-submit" %>
		  </div>
		</div>
  <% end %>
<% end %>

app/views/greetings/_form_fields.html.erb
<%= section_header "Create a New Greeting" %>

<%= fr "Welcome Message",
	f.text_field(:welcome_message, placeholder: 'Drank coffee today?'),
	id: "tour-welcome",
	info: "This message will be shown to customers as they enter your store." %>

<%= fr "Check-in Points",
	row: "row bb", info: "Customers can be awarded points for checking into your store on a daily, weekly, or monthly basis." do %>
	<div class="row">
		<div class="col-xs-12 col-sm-5">
			<%= f.number_field :welcome_reward, placeholder: 'ie: 100', min: 0 %>
		</div>
		<div class="col-xs-5 col-sm-2">
			<%= f.label "per", class: "inline" %>
		</div>
		<div class="col-xs-7 col-sm-5">
			<%= f.select :welcome_wait_time, %w(day week month) %>
		</div>
	</div>
<% end %>

<%= fr "Exit Message",
	f.text_field(:exit_message, placeholder: 'Have a great day!'),
	id: "tour-exit",
	info: "This message is shown to customers as they exit your store." %>

<%= fr "",
	{info: "You can display a special campaign to your customers as they exit to entice them to return."} do %>
	<%= cbox(
		"attach",
		"Attach a Campaign?",
		checkbox: {
			checked: !(greeting_campaign.nil?),
			data: {
				toggle: "collapse", 
				target: "#collapseCampaign"
			}
		}
	) %>
<% end %>

<div class="collapse <%= "in" if !(greeting_campaign.nil?) %>" id="collapseCampaign">
	<%= fr "Campaign",
		f.collection_select(:campaign_id, @campaigns, :id, :title, prompt: 'Choose a campaign', class: 'extraSpace') %>
	
	<%= fr "Valid for",
		id: "tour-valid",
		info: "A customer must return to your store within the assigned timeframe to receive the campaign." do %>
		<div class="row">
			<div class="col-xs-5">
				<%= f.number_field :campaign_wait_time_quantity, placeholder: "(enter 0 for no restriction)", min: 0 %>
			</div>
			<div class="col-xs-7">
				<%= f.select :campaign_wait_time_span, %w(days weeks months) %>
			</div>
		</div>
  <% end %>
</div>

app/views/greetings/edit.html.erb
<% content_for(:page_title) { "Push Greetings" } %>

<%= render 'form' %>

app/views/greetings/index.html.erb
<% hopscotch %>
<% content_for(:page_title) { "Push Greetings" } %>

<%= wrapper do %>
  <%= section_header "Your Greetings" %>

  <% if @greetings %>
    <%= link_to 'New Greeting', new_greeting_path, id: "tour-new-greeting", class: 'btn btn-new' %>

    <div class="table-responsive">
      <table data-toggle="table" data-toolbar="#custom-toolbar" data-show-columns="false" data-search="false" data-show-refresh="false" data-show-filter="false" data-show-toggle="false" data-show-export="false" data-pagination="true" data-pagination-v-align="both" data-striped="true" class="table table-hover table-condensed table-bordered">
        <thead>
          <tr>
            <th class="first"></th>
            <th data-align="left" data-sortable="true">Welcome Msg.</th>
            <th data-align="left" data-sortable="true">Reward</th>
            <th data-align="left" data-sortable="true">Exit Msg.</th>
            <th data-align="left" data-sortable="true">Attached Campaign</th>
            <th data-align="left" data-sortable="true">Assigned Locations</th>
            <th data-align="left" data-sortable="false">Options</th>
          </tr>
        </thead>
        <tbody>
          <% @greetings.includes(:campaign, :locations).each do |greeting| %>
            <tr>
              <td><%= active_circle(greeting.assigned_to_location?) %></td>
              <td><%= link_to greeting.welcome_message, edit_greeting_path(greeting) %></td>
              <td><%= greeting.welcome_reward %></td>
              <td><%= link_to greeting.exit_message, edit_greeting_path(greeting) %></td>
              <td><%= link_to(greeting.campaign.title, greeting.campaign) rescue "N/A" %></td>
              <td class="overflow-more relative" data-entry-limit="3"><%= greeting.locations_string %></td>
              <td>
                <%= link_to 'edit', edit_greeting_path(greeting), class: 'option edit' %>
                <%= link_to 'delete', greeting, method: :delete, data: { confirm: 'Deleting this greeting cannot be undone. Are you sure you want to do this?' }, class: 'option delete' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  <% else %> <%# !greetings %>

    <div class="row">
      <div class="col-xs-12">
        <h3 id="no-data">Push Greeting allow you to make a first and last impression each time a customer visits your store.</h3>
      </div>
    </div>

  <% end %> <%# greetings? %>
<% end %> <%# -wrapper %>

app/views/greetings/new.html.erb
<% hopscotch %>
<% content_for(:page_title) { "Push Greetings" } %>

<%= render 'form' %>

app/views/greetings/update.html.erb
<h1>Greetings#update</h1>
<p>Find me in app/views/greetings/update.html.erb</p>