config/routes.rb
Rails.application.routes.draw do

  apipie
  # if Rails.env.development? || Rails.env.test?

    # Beacons
    get   '/beacon/:key',     to: 'beacons#edit',     as: 'edit_beacon'
    patch '/beacon/:key',     to: 'beacons#update',   as: 'beacon'
    get   '/beacon/success',  to: 'beacons#success',  as: 'beacon_success'

    # Businesses
    get '/business', to: 'businesses#edit', as: 'edit_business'
    resources :businesses, only: [:new, :create, :update]

    # Customers
    get  '/customers/:status/(:export/:list)',  to: 'customers#index',   as: 'customers',  constraints: {status: /(all|active|inactive)/}, defaults: {status: 'all'}
    post '/customers/import',                   to: 'customers#import',  as: 'import_customers'

    # Greetings
    resources :greetings, except: [:show]


    # All Receipts
    resources :receipts, only: [:index, :show]

    # All Campaigns
    get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
    get '/campaigns/new/:type',         to: 'campaigns#new',    as: 'new_campaign', constraints: {type: /(coupon|reward|special)/}, defaults: {type: 'coupon'}
    resources :campaigns, except: [:index, :new]

    # Locations and Locationable Routes
    resources :locations, except: [:destroy] do
      get     '/subscription/success',    to: 'subscriptions#success',   as: 'subscription_success'
      get     '/subscription',            to: 'subscriptions#show',      as: 'subscription'
      get     '/subscription/new',        to: 'subscriptions#new',       as: 'new_subscription'
      post    '/subscription/new',        to: 'subscriptions#create',    as: 'subscriptions'
      delete  '/subscription/cancel',     to: 'subscriptions#destroy',   as: 'cancel_subscription'
      patch '/confirm',   to: 'locations#confirm', as: 'confirm'

      # Locationable routes
      get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
      resources :campaigns, only: :show
    end


    # Users
    devise_for :users, skip: [:sessions], controllers: {
      confirmations:  'users/confirmations',
      registrations:  'users/registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

    devise_scope :user do
      get '/users/login'     => 'devise/sessions#new',     as: :new_user_session
      post '/users/login'    => 'devise/sessions#create',  as: :user_session
      delete '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session

      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup'   => 'omniauth_callbacks#setup'
    end

    get '/users/toggleSidebar', to: "users#toggleSidebar"
    post '/users/endTour', to: "users#endTour"

    # Admins
    devise_for :admins

    namespace :admin do
      root 'pages#dashboard'
      resources :receipts, only: [:index, :update, :destroy]
    end

    # Normal Pages
    get '/lock_business/:id',   to: 'businesses#lock'
    get '/locked',   to: 'pages#locked_business',  as: 'locked_business'
    get '/subscription_canceled',   to: 'pages#subscription_canceled',  as: 'subscription_canceled'


    # Root
    root 'pages#dashboard'
  # end


  ## API
  namespace :api do
    api versions: 1, module: "v1" do
      # Customer actions
      post '/customers/sign_in',            to: 'customers#sign_in'
      post '/customers/sign_out',           to: 'customers#sign_out'
      post '/customers/check_in',           to: 'customers#check_in'
      post '/customers/check_out',          to: 'customers#check_out'
      post '/customers/notification_token', to: 'customers#notification_token'
      get '/customers/profile',             to: 'customers#show'
      get '/customers/feed',                to: 'customers#feed'
      get '/customers/visits',              to: 'customers#visits'

      # Temp test for notifications
      # get '/customers/notification',        to: 'customers#get_notification'

      # Finds a location via UID
      get '/beacons/:uid/location',            to: 'locations#show'

      # Locations
      get '/locations/:id',                     to: 'locations#show'
      get '/locations/:id/campaigns',           to: 'campaigns#index'
      # Fetch nearest 20 beacons. Similar to fetch map, but return top 20 by proximity
      get '/locations/near/:lat/:lon',          to: 'locations#fetch_nearby', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}
      get '/locations/map/:lat/:lon/:distance', to: 'locations#fetch_map', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}

      # Campaigns
      resources :campaigns, only: [:show]

      # Receipts
      post '/receipts',              to: 'receipts#create'
      get  '/receipts(/:status)',   to: 'receipts#index', defaults: {status: 'untouched'}

      # Redemptions
      resources :redemptions, only: [:index, :create]

      # Referrals
      resources :share_links, only: [:show, :create]
    end
  end

end

app/views/shared/_crop_modal.html.erb
<%# 

CROP MODAL

Notes:
- To allow for multiple upload modals on a page, there's a default 
  id (#cropImageModal) and the ability to pass-in a custom id
  ex (in erb): render 'shared/crop_modal', resource: @location.location_photos[0], id: "cropImageModal-0"

 %>


<%# Default ID %>

<% id ||= "cropImageModal" %>



<%# Modal module id%>

<%= modal :large, id: id, classes: "js-cropModal", title: "Live Image Crop",
    body: capture { %>

    <div class="row mb <%= id %>">
      <div class="col-xs-12">
        <div class="file-upload">
          <a href="#" class="findImage btn btn-browse upload-trigger">Browse</a>
          <%= file_field_tag "uploaded_image", accept: "image/*", class: "file_field" %>
          <span>Choose a file</span>
        </div>
      </div>
    </div>
    
    <div class="row form-set">
     <div class="col-md-6">
    
         <div class="imageBox avatarBox">
            <div class="thumbBox"></div>
            <div class="spinner" style="display: none">
              Loading...
            </div>
         </div>
    
         <div class="action">
             <input type="button" class="btnZoomIn avatar btn btn-default disabled" value="+">
             <input type="button" class="btnZoomOut avatar btn btn-default disabled" value="-">
             <input type="button" class="btnCrop avatar btn btn-default disabled" value="Preview Crop">
         </div>
     </div>
     <div class="col-md-6">
         <div class="cropped cropped_image">
          <%= image_tag resource.image.url(:index), style: "width:420", id: "image-c", class: "thumbnail" %>
         </div>
     </div>
    </div>
<% }, footer: capture { %>
  <button type="button" class="btnSaveClose btn btn-default pull-right" data-dismiss="modal" aria-label="Close">
    Save and Close Window
  </button>
<% } %>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
	<div class="flash <%= type %>">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<% unless object.nil?%>
						<i class="fa fa-exclamation-triangle"></i>
						<p>
							<%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
						</p>
						
						<ul>
					    <% object.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
					  </ul>
				  <% end %>

				  <% if flash[:alert] %>
						<i class="fa fa-exclamation-triangle"></i>
						<p><%= flash[:alert] %></p>
				  <% elsif flash[:notice] %>
						<i class="fa fa-star"></i>
				  	<p><%= flash[:notice] %></p>
				  <% elsif flash[:success] %>
						<i class="fa fa-check"></i>
				  	<p><%= flash[:success] %></p>
					<% end %>

				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_getting_started.html.erb
<h2>Getting started</h2>
-----

app/views/shared/_location_selector.html.erb
<select id="locationFilter" class="mr3"> <%# margin-right here to account for angle icon %>
	<option value="/campaigns">All Locations</option>
	<% current_user.locations.each do |l| %>
		<%
			url_for_opts = {
				controller: type_of[:controller], 
				action: type_of[:action]
			}
			if type_of[:use_id_for_location]
				url_for_opts[:id] = l.id.to_s
			else
				url_for_opts[:location_id] = l.id.to_s
			end
		%>
	  <option value="<%= url_for(url_for_opts) %>"><%= l.title %></option>
  <% end %>
	<option value="<%= new_location_url %>">+ New Location</option>
</select>

app/views/shared/_modal.html.erb
<div class="modal fade <%= classes %>" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="<%= id %>">
  <div class="modal-dialog <%= size %>" role="document">
    <div class="modal-content">
      <% if title %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"><%= title %></h4>
        </div>
      <% end %>

      <div class="modal-body">
        <%= body %>
      </div>

      <% if footer %>
        <div class="modal-footer">
          <%= footer %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_progress_steps.html.erb
<% unless current_user.business.published? %>

	<div class="profile-progress">
		<div class="container">

			<div class="profile-progress-head text-center">
				<span><%= image_tag 'ico_finger.png', id: "progress_finger" %></span>
				<em>Let's Get Started!</em>
			</div>


			<ul class="list-inline profile-progress-list">
				<%# progress_steps is defined in the application_helper %>
				<% progress_steps[:steps].each do |st| %>
					<li>
						<%= check_or_x st[:check_if] %>
						<%= link_to st[:name], st[:url], data: {toggle: "tooltip", placement: "top"}, title: st[:info] %>
					</li>
				<% end %>
			</ul>
	
			<div class="profile-progress-bar hidden-xs">
				<h5><%= progress_steps[:percent] %>% Complete</h5>
				<span>
					<em style="width: <%= progress_steps[:percent] %>%"></em>
				</span>
			</div>

		</div>
	</div>

<% end %>

app/views/shared/_toggle_section_btns.erb
<div class="fit toggle-section_buttons mt1 mb1">
  <button class="left toggle-section_btn-prev">
    Previous
  </button>
  <button class="button right toggle-section_btn-next">
    Next
  </button>
  <div class="clearfix"></div>
</div>