config/routes.rb
Rails.application.routes.draw do

  apipie
  # if Rails.env.development? || Rails.env.test?

    # Beacons
    get   '/beacon/:key',     to: 'beacons#edit',     as: 'edit_beacon'
    patch '/beacon/:key',     to: 'beacons#update',   as: 'beacon'
    get   '/beacon/success',  to: 'beacons#success',  as: 'beacon_success'

    # Businesses
    get '/business', to: 'businesses#edit', as: 'edit_business'
    resources :businesses, only: [:new, :create, :update]

    # Customers
    get  '/customers/:status/(:export/:list)',  to: 'customers#index',   as: 'customers',  constraints: {status: /(all|active|inactive)/}, defaults: {status: 'all'}
    post '/customers/import',                   to: 'customers#import',  as: 'import_customers'

    # Greetings
    resources :greetings, except: [:show]


    # All Receipts
    resources :receipts, only: [:index, :show]

    # All Campaigns
    get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
    get '/campaigns/new/:type',         to: 'campaigns#new',    as: 'new_campaign', constraints: {type: /(coupon|reward|special)/}, defaults: {type: 'coupon'}
    resources :campaigns, except: [:index, :new]

    # Locations and Locationable Routes
    resources :locations, except: [:destroy] do
      get     '/subscription/success',    to: 'subscriptions#success',   as: 'subscription_success'
      get     '/subscription',            to: 'subscriptions#show',      as: 'subscription'
      get     '/subscription/new',        to: 'subscriptions#new',       as: 'new_subscription'
      post    '/subscription/new',        to: 'subscriptions#create',    as: 'subscriptions'
      delete  '/subscription/cancel',     to: 'subscriptions#destroy',   as: 'cancel_subscription'
      patch '/confirm',   to: 'locations#confirm', as: 'confirm'

      # Locationable routes
      get '/campaigns/(:type)/(:status)', to: 'campaigns#index',  as: 'campaigns',    constraints: {status: /(all|featured|active|inactive|upcoming)/, type: /(all|coupon|reward|special)/}, defaults: {status: 'all', type: 'all'}
      resources :campaigns, only: :show
    end


    # Users
    devise_for :users, skip: [:sessions], controllers: {
      confirmations:  'users/confirmations',
      registrations:  'users/registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

    devise_scope :user do
      get '/users/login'     => 'devise/sessions#new',     as: :new_user_session
      post '/users/login'    => 'devise/sessions#create',  as: :user_session
      delete '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session

      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup'   => 'omniauth_callbacks#setup'
    end

    get '/users/toggleSidebar', to: "users#toggleSidebar"
    post '/users/endTour', to: "users#endTour"

    # Admins
    devise_for :admins

    namespace :admin do
      root 'pages#dashboard'
      resources :receipts, only: [:index, :update, :destroy]
    end

    # Normal Pages
    get '/lock_business/:id',   to: 'businesses#lock'
    get '/locked',   to: 'pages#locked_business',  as: 'locked_business'
    get '/subscription_canceled',   to: 'pages#subscription_canceled',  as: 'subscription_canceled'


    # Root
    root 'pages#dashboard'
  # end


  ## API
  namespace :api do
    api versions: 1, module: "v1" do
      # Customer actions
      post '/customers/sign_in',            to: 'customers#sign_in'
      post '/customers/sign_out',           to: 'customers#sign_out'
      post '/customers/check_in',           to: 'customers#check_in'
      post '/customers/check_out',          to: 'customers#check_out'
      post '/customers/notification_token', to: 'customers#notification_token'
      get '/customers/profile',             to: 'customers#show'
      get '/customers/feed',                to: 'customers#feed'
      get '/customers/visits',              to: 'customers#visits'

      # Temp test for notifications
      # get '/customers/notification',        to: 'customers#get_notification'

      # Finds a location via UID
      get '/beacons/:uid/location',            to: 'locations#show'

      # Locations
      get '/locations/:id',                     to: 'locations#show'
      get '/locations/:id/campaigns',           to: 'campaigns#index'
      # Fetch nearest 20 beacons. Similar to fetch map, but return top 20 by proximity
      get '/locations/near/:lat/:lon',          to: 'locations#fetch_nearby', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}
      get '/locations/map/:lat/:lon/:distance', to: 'locations#fetch_map', constraints: {lat: /\-?\d+(.\d+)?/, lon: /\-?\d+(.\d+)?/}

      # Campaigns
      resources :campaigns, only: [:show]

      # Receipts
      post '/receipts',              to: 'receipts#create'
      get  '/receipts(/:status)',   to: 'receipts#index', defaults: {status: 'untouched'}

      # Redemptions
      resources :redemptions, only: [:index, :create]

      # Referrals
      resources :share_links, only: [:show, :create]
    end
  end

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  enum status: [:untouched, :approved, :rejected]

  include DatePickable
  datepicker [:purchased_on]


  belongs_to :redemption
  has_one :location, through: :redemption
  has_one :business, through: :location
  has_one :customer, through: :redemption

  validates_presence_of :redemption_id
  validates_presence_of :amount, :purchased_on, on: [:update], if: "status == 'approved'"
  validates_presence_of :reject_reason, if: "status == 'rejected'"

  has_attached_file :image,
                    styles: { medium: '500x500#' }
  validates_attachment_presence :image
  validates_attachment_content_type :image,
                                    content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"]


  scope :from_today, -> {
    where( updated_at: (Date.today)..(Date.today + 23.hours + 59.minutes + 59.seconds) )
  }


  def self.reject_reasons
    [
      {id: 'expired',           label: 'Date invalid or missing',          reason:  "The date is not shown or is greater than 30 days ago."},
      {id: 'invalid_location',  label: 'Location does not match receipt',  reason:  "The location does not match the receipt."},
      {id: 'unable_to_read',    label: 'Low-quality image',                reason:  "The image is too blurry (unable to read)."},
    ]
  end

  def reward_points
    amount.floor.to_i
  end

  def location
    redemption.location rescue nil
  end

  ## Below is for the API
  def attributes
    super.merge({image_url: image_url})
  end

  def image_url
    image.url
  end
  ##

end

app/controllers/admin/receipts_controller.rb
class Admin::ReceiptsController < Admin::AdminController
  before_action :set_receipt, only: [:update, :destroy]

  def index
    if Rails.env.development?
      Receipt.update_all(status: 'untouched') ## TEMP TEST DEV LOCAL
    end
    @receipt = Receipt.untouched.first
  end

  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        if @receipt.approved?
          unless @receipt.redemption.location.business.nil? # to prevent rspec test errors
            @receipt.redemption.award_points_to_customer!
            @receipt.redemption.award_share_points!
          end
        end
        format.html { redirect_to admin_receipts_url, notice: 'Receipt was successfully updated.' }
        format.js
      else
        format.html { render :index }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to admin_receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params[:receipt][:status] ||= "rejected"
      params.require(:receipt).permit(:location_id, :purchased_on, :amount, :reject_reason, :status)
    end
end

app/controllers/api/v1/receipts_controller.rb
class Api::V1::ReceiptsController < Api::V1::BaseController
	resource_description do
	  short 'Receipts are associated with redemptions and are uploaded by the customer for approval'
	  meta :receipt => Receipt.column_names
	end

	api!
	desc "Create a new receipt with the given params."
	error code: 422, desc: "Invalid receipt params were given (or invalid image)."
	param :receipt, Hash, required: true do
		param :redemption_id, :number, desc: "The associated redemption_id (Required IF related to a campaign)"
		param :location_id, :number, desc: "The associated location_id (Required IF this is a receipt that is not associated with a campaign redemption)"
		param :image, File, desc: "The receipt image", required: true
	end
	example "If a receipt is associated with a prior redemption, you MUST include the redemption ID. Otherwise, if this receipt is being uploaded by itself and is not related to a campaign's redemption, you MUST pass the location_id that the receipt is associated with. Returns 200 OK"
	def create
		# If the redemption ID is nil, we create the redemption so we can
		# assign it to the receipt
		if params[:receipt][:location_id]
			redemption_id = Redemption.create(customer: current_customer, location_id: params[:receipt][:location_id]).id
		else
			redemption_id = params[:receipt][:redemption_id]
		end

		receipt = Receipt.new(image: params[:receipt][:image], redemption_id: redemption_id)
		
		unless receipt.save
			error! :invalid_resource, receipt.errors
		end
	end

	api!
	desc "Shows the receipts and status"
	param :status, ["untouched", "approved", "rejected", "all"], desc: "The status of the receipts shown", default: "untouched"
	example <<-EOS
	{
	  "count" => 1,
	  response => Array[
	    Hash {
        "id" => ,
        "purchased_on" => ,#is updated by the admin
        "amount" => ,#is 0 until admin sets amount
        "reject_reason" => ,#is blank unless rejected
        "created_at" => ,#when the receipt was uploaded initially
        "status" => ,
        "actioned_on" => ,#when the receipt was approved/rejected
        "image_file_name" => ,
        "location" => Hash {Location Data}
	    }
	  ]
	}
	EOS
	def index
		params[:status] ||= 'untouched'
		receipts = current_customer.receipts
		receipts = receipts.where(status: params[:status]).all unless params[:status] == 'all'

		collection receipts, include: [:location, :business], methods: :image_url, only: [
			:id,
			:purchased_on,
			:amount,
			:reject_reason,
			:created_at,
			:status,
			:actioned_on,
			:image_file_name,
			:image_url
		]
	end


 	private
 		def valid_params
      params.require(:receipt).permit(:redemption_id, :image).merge!(customer_id: current_customer.id)
 		end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  def index
    if params[:location_id]
      receipts = current_user.locations.where(id: params[:location_id]).first.receipts
    else
      receipts = current_user.business.receipts
    end

    # Validate each query-string param
    %w(start_date end_date).each do |d|
      params[d.to_s] = Date.parse(params[d.to_s]) rescue nil
    end

    if params[:start_date] && params[:end_date]
      receipts = receipts.where(purchased_on: params[:start_date]..params[:end_date])
    elsif params[:start_date]
      receipts = receipts.where(purchased_on: params[:start_date])
    end

    @approved_receipts = receipts.approved
  end


  def show
    @receipt = current_user.business.receipts.find(params[:id])

    respond_to do |format|
      format.js { render :show }
    end
  end

  
  private
    def receipt_params
      #permit nothing
      params.require(:receipt).permit()
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :purchased_on %><br>
    <%= f.date_select :purchased_on %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, min: 0 %>
  </div>
  <div class="field">
    <%= f.label :approved_on %><br>
    <%= f.date_select :approved_on %>
  </div>
  <div class="field">
    <%= f.label :rejected_on %><br>
    <%= f.date_select :rejected_on %>
  </div>
  <div class="field">
    <%= f.label :reject_reason %><br>
    <%= f.text_field :reject_reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/_receipt_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title">Receipt #<%= receipt.id %></h4>
</div>
<div class="modal-body">
  
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= image_tag receipt.image.url(:medium), style: "width: 300px" %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <table>
        <tr>
          <td>Receipt ID:</td>
          <td><%= receipt.id %></td>
        </tr>
        <tr>
          <td>Location:</td>
          <td><%= receipt.location.title %></td>
        </tr>
        <tr>
          <td>Purchased on:</td>
          <td><%= receipt.purchased_on %></td>
        </tr>
        <tr>
          <td>Amount:</td>
          <td><%= receipt.amount %></td>
        </tr>
        <tr>
          <td>Approved on:</td>
          <td><%= receipt.updated_at %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= link_to 'Report a problem', "mailto:support@zippyspot.com?subject=Receipt Issue [#{receipt.id}]", class: "btn btn-primary" %>
</div>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<% content_for(:page_title) { "Receipts" } %>

<%= wrapper do %>
  <% unless @approved_receipts.blank? %>
    <% hopscotch "receipts-index-has-receipts" %>
    <div class="row mb2">
      <div class="col-xs-12 col-sm-8">
        <h2>Verified Receipts</h2>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= render 'shared/location_selector', type_of: {controller: :receipts, action: :index} %>
      </div>
    </div>

    <div class="filter-options">
      <div class="left mb3 mr4">
        <h4 id="tour-filter" class="caps m0">Filter<br> by Date:</h4>
      </div>
      <%# Filter form %>
      <form action="<%= receipts_url %>" method="get">

        <%# Start date %>
        <div class="left mr3 input-group date" data-format="yyyy-mm-dd">
          <div class="left">
            <input class="m0" style="width: 120px" type="text" name="start_date" placeholder="start" value="<%= params[:start_date] %>">
          </div>
          <div class="left">
            <div class="input-group-addon"></div>
          </div>
        </div>
        
        <%# End date %>
        <div class="left mr3 input-group date mb2" data-format="yyyy-mm-dd">
          <div class="left">
            <input class="m0" style="width: 120px" type="text" name="end_date" placeholder="end" value="<%= params[:end_date] %>">
          </div>
          <div class="left">
            <div class="input-group-addon"></div>
          </div>
        </div>

        <%# Submit %>
        <div class="pt2">
          <input type="submit" class="no-fit btn btn-submit caps m0">
          <% if params[:start_date] %>
            <%# We only need to show this if the params are set.
                Since end_date is optional we only check for the
                presence of start_date.
            %>
            <a href="<%= receipts_url %>" class="no-fit btn btn-reject m0">Clear</a>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </form>
    </div>

    <div class="table-responsive">
      <table id="tour-table" data-toggle="table" data-toolbar="#custom-toolbar" data-show-columns="false" data-search="false" data-show-refresh="false" data-show-filter="false" data-show-toggle="false" data-show-export="false" data-pagination="true" data-pagination-v-align="both" data-striped="true" class="table table-hover table-condensed table-bordered">
        <thead>
          <tr>
            <th class="first" data-align="left" data-sortable="true">ID</th>
            <th data-align="left" data-sortable="true">Image</th>
            <th data-align="left" data-sortable="true" data-sorter="dateSorter">Date</th>
            <th data-align="left" data-sortable="true">Amount</th>
          </tr>
        </thead>
        <tbody>
          <% @approved_receipts.each do |receipt| %>
            <tr>
              <td><%= receipt.id %></td>
              <td><%= link_to 'View Receipt', receipt, remote: true, data: {toggle: 'modal', target: '#viewReceiptModal'} %>
              <td><%= receipt.purchased_on %></td>
              <td><%= receipt.amount %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>


    <%# Modal %>
    <div class="modal fade" id="viewReceiptModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        </div>
      </div>
    </div>

  <% else %> <%# !receipts %>
    <% hopscotch %>
    <div id="tour-no-records">
      <h2 class="nowrap">No Receipts!</h2>
      <p>There are no approved receipts available to show.</p>
    </div>

  <% end %> <%# receipts? %>
<% end %> <%# -wrapper %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title">Receipt #<%= @receipt.id %></h4>
</div>
<div class="modal-body">
  
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= image_tag @receipt.image.url(:medium) %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <table>
        <tr>
          <td>Receipt ID:</td>
          <td><%= @receipt.id %></td>
        </tr>
        <tr>
          <td>Location:</td>
          <td><%= @receipt.location.title %></td>
        </tr>
        <tr>
          <td>Purchased on:</td>
          <td><%= @receipt.purchased_on %></td>
        </tr>
        <tr>
          <td>Amount:</td>
          <td><%= @receipt.amount %></td>
        </tr>
        <tr>
          <td>Approved on:</td>
          <td><%= @receipt.updated_at %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= link_to 'Report a problem', "mailto:support@zippyspot.com?subject=Receipt Issue [#{@receipt.id}]", class: "btn btn-primary" %>
</div>

app/views/receipts/show.js.erb
$('#viewReceiptModal .modal-content').html('<%= j( render("receipt_modal", receipt: @receipt) ) %>');